services:

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - student_network
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
  db: 
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=students
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - student_network
volumes:
  postgres_data:

networks:
  student_network: